#ifndef ERRORS_H
#define ERRORS_H

#define STATUS_OK (0x00)
#define STATUS_ERR_NO_DATA (0x01)
#define STATUS_ERR_NO_SEQ_NUM (0x02)
#define STATUS_ERR_SETTING_CHECKSUM (0x03)
#define STATUS_ERR_CHECKSUM_MISMATCH (0x04)
#define STATUS_ERR_MALLOC (0x05)
#define STATUS_ERR_NULL_PTR (0x06)
#define STATUS_ERR_SEQ_NUM_MISMATCH (0x07)
#define STATUS_ERR_READ_FAILED (0x08)

#endif