#ifndef ERRORS_H
#define ERRORS_H

#define STATUS_OK (0x00)
#define STATUS_ERR_NO_DATA (0x01)
#define STATUS_ERR_NO_SEQ_NUM (0x02)
#define STATUS_ERR_CHECKSUM (0x03)
#define STATUS_ERR_CHECKSUM_MISMATCH (0x04)
#define STATUS_ERR_MALLOC (0x05)

#endif